using System.Linq;
using NUnit.Framework;
using UnityOpenMcpBridge;

namespace UnityOpenMcpBridge.Tests
{
    // Pins the generated token-estimate table (BridgeToolTokenEstimates) against
    // the same shape of sanity bounds the competing token-counter surface uses:
    // every catalog tool resolves to a positive estimate, no single tool is
    // absurdly large, and the catalog total stays bounded. The exact numbers
    // shift as tools are added/removed — these tests guard the INVARIANTS, not
    // specific values. If the generated table ever drifts from the catalog,
    // BridgeToolCatalogTests.Build_CoversKnownToolsUnion-style coverage catches
    // that separately; here we assert the estimate surface itself is sound.
    //
    // The table is regenerated by scripts/generate-token-estimates.mjs from the
    // MCP-server tool schemas; the CI drift gate
    // (.github/workflows/version-sync.yml) fails any PR where the checked-in
    // table disagrees with the source.
    public static class BridgeToolTokenEstimatesTests
    {
        // Every tool the catalog surfaces must resolve to a positive estimate.
        // A null here means the codegen table missed a catalog tool — either the
        // tool is not in mcp-server/src/tools (a bridge-only tool with no server
        // schema) or the table is stale. Both are worth surfacing.
        [Test]
        public static void CatalogTools_AllHavePositiveEstimate()
        {
            var items = BridgeToolCatalog.Build();
            var missing = items.Where(i => !i.TokenEstimate.HasValue || i.TokenEstimate.Value <= 0).ToList();
            Assert.IsEmpty(missing,
                "Every catalog tool must have a positive token estimate. " +
                "Tools without one: " +
                string.Join(", ", missing.Select(i => i.Name)));
        }

        // No single tool should be absurdly large — a tool over this bound is a
        // schema that has grown unwieldy (or a codegen bug). The bound mirrors
        // the competitor's < 10000 sanity check.
        [Test]
        public static void CatalogTools_NoToolExceedsReasonableBound()
        {
            const int maxPerTool = 10000;
            var offenders = BridgeToolCatalog.Build()
                .Where(i => i.TokenEstimate.HasValue && i.TokenEstimate.Value >= maxPerTool)
                .ToList();
            Assert.IsEmpty(offenders,
                $"No tool should estimate >= {maxPerTool} tokens — a schema this large is " +
                "either unwieldy or a codegen bug. Offenders: " +
                string.Join(", ", offenders.Select(i => $"{i.Name} (~{i.TokenEstimate})")));
        }

        // The catalog total must be non-zero and bounded. The chars/4 heuristic
        // over ~290 tools currently lands near 75K; the bound leaves headroom for
        // growth without letting a runaway schema pass silently. Mirrors the
        // competitor's < 5 000 000 catalog-total check.
        [Test]
        public static void CatalogTotal_IsBoundedAndNonZero()
        {
            const int maxTotal = 5_000_000;
            var total = BridgeToolCatalog.Build()
                .Where(i => i.TokenEstimate.HasValue)
                .Sum(i => i.TokenEstimate.Value);
            Assert.Greater(total, 0, "Catalog token total must be non-zero.");
            Assert.Less(total, maxTotal,
                $"Catalog token total (~{total}) exceeds the {maxTotal} sanity bound — " +
                "either the tool schemas ballooned or the codegen heuristic broke.");
        }

        // Format() is the human-readable rendering (1.2K / 74.6K / plain int).
        // Pin the convention so the UI chip + header read identically to the
        // competing surface (the whole point of mirroring the format verbatim).
        [Test]
        public static void Format_MatchesKConvention()
        {
            Assert.AreEqual("0", BridgeToolTokenEstimates.Format(0));
            Assert.AreEqual("999", BridgeToolTokenEstimates.Format(999));
            // >= 1000 renders as thousands with one decimal.
            Assert.AreEqual("1K", BridgeToolTokenEstimates.Format(1000));
            Assert.AreEqual("1.2K", BridgeToolTokenEstimates.Format(1200));
            Assert.AreEqual("74.6K", BridgeToolTokenEstimates.Format(74555));
        }

        // Known group ids round-trip: the canonical core / typed-editor groups
        // must resolve to a non-null Group, and always-visible meta-tools
        // (capabilities, ping, manage_tools) resolve to null. Guards the
        // group-assignment half of the generated table.
        [Test]
        public static void GroupFor_KnownAssignmentsResolve()
        {
            // core group tools.
            Assert.AreEqual("core", BridgeToolTokenEstimates.GroupFor("unity_open_mcp_ping"));
            Assert.AreEqual("core", BridgeToolTokenEstimates.GroupFor("unity_open_mcp_execute_csharp"));
            // typed-editor group tool.
            Assert.AreEqual("typed-editor", BridgeToolTokenEstimates.GroupFor("unity_open_mcp_gameobject_create"));
            // domain group tool.
            Assert.AreEqual("navigation", BridgeToolTokenEstimates.GroupFor("unity_open_mcp_navigation_surface_add"));
        }
    }
}
