// M31 Plan 6 / T6.6 — light `helpText` + `versionText` module.
//
// These two formatters are needed on the `--help` / `--version` fast paths,
// which must NOT pull in the heavy command/router import graph (commands.ts
// imports ALL_TOOLS, the ~270-tool surface). Splitting them into their own
// module lets cli.ts import only this light file for the fast paths and defer
// the heavy `./commands.js` + `../routers.js` imports to a dynamic `import()`
// that runs only when a real subcommand is dispatched.
//
// `commands.ts` re-exports both so existing imports from `./commands.js`
// (commands.test.ts) keep resolving.

import {
  PORT_ENV_VAR,
  PROJECT_PATH_ENV_VAR,
} from "../constants.js";

export function helpText(binName: string): string {
  return [
    `Usage: ${binName} <command> [options]`,
    "",
    "Thin CLI for Unity Open MCP — wraps the MCP server for CI / scripting.",
    "When invoked with no command, runs the stdio MCP server (MCP client mode).",
    "",
    "Commands:",
    "  ping                          One /ping against the bridge; exit 0 if ready.",
    "  wait-for-ready                Poll /ping until the bridge is ready; exit 0/non-zero.",
    "  status                        Show resolved bridge port, instance lock, and readiness.",
    "  run-tool <name>               Invoke an MCP tool by name; print its JSON result.",
    "  stream-events                 Drain bridge SSE events (console logs + state) to stdout.",
    "  verify [paths...]             Run a verify scan; exit code reflects severity (4-level).",
    "  baseline create|update        Create/refresh the regression baseline JSON file.",
    "  regression check              Compare current scan against the baseline; exit on regression.",
    "  update [--check]              Check for or apply an MCP server update.",
    "  setup --client C              Install packages, MCP config, and the core skill (cwd = project).",
    "  --help, -h                    Show this help.",
    "  --version, -V                 Print the package version.",
    "",
    "Exit codes:",
    "  0  success        no issues / no regression.",
    "  1  warnings       only warnings/info below the fail threshold.",
    "  2  errors         errors present, or a regression was detected.",
    "  3  timeout        bridge never became reachable, or a call timed out.",
    " 10  update         --check found a newer MCP server version.",
    " 11  lookup failed  npm and GitHub version checks both failed.",
    " 12  install failed npm could not apply the requested update.",
    "",
    "Options:",
    "  --json                        Emit JSON instead of human-readable output (all commands).",
    `  --project <path>, -P <path>   Unity project path, absolute or relative to the cwd (default: ${PROJECT_PATH_ENV_VAR}; setup: the cwd).`,
    "  --project-from-cwd            Resolve the Unity project from the current directory.",
    "  --unity-subpath <rel>         Unity project subfolder under the workspace (monorepo).",
    `  --port <n>, -p <n>            Bridge port override (default: ${PORT_ENV_VAR}).`,
    "  --timeout-ms <n>              Ping / wait-for-ready timeout in ms.",
    "  --interval-ms <n>             wait-for-ready poll interval in ms.",
    "  --args '<json>'               JSON object of tool args (run-tool).",
    "  --arg key=value               One tool arg (run-tool, repeatable; JSON-parsed if valid).",
    "  --max-events <n>              stream-events: max events to drain per pull.",
    "  --follow                      stream-events: keep polling until interrupted (CI log tap).",
    "  --check                       update: check only; do not change the install.",
    "  --client <id>                 setup: cursor | claude | vscode | codex | opencode | agents.",
    "  --skip-skill                  setup: do not copy the bundled core skill.",
    "  --dry-run                     setup: report intended writes without changing files.",
    "  --layout <l>                  setup: unity-root (default) | monorepo.",
    "  --workspace <path>            setup: repository root the AI client is opened on (absolute or relative).",
    "  --portable, --no-portable     setup: force a committable config, or the absolute path.",
    "  --wrapper                     setup: also write the committed MCP wrapper script.",
    "  --mode <m>                    verify: auto (default) | scan-paths | validate-edit.",
    "  --fail-on-severity <s>        verify: error | warn | info | verbose | never.",
    "  --profile <p>                 verify: compact (default) | balanced | full.",
    "  --include-rules <a,b>         verify: comma-separated rule allow-list.",
    "  --exclude-rules <a,b>         verify: comma-separated rule deny-list.",
    "  --platform-profile <p>        verify/baseline/regression: mobile | console | desktop.",
    "  --baseline-path <path>        baseline/regression: path to the baseline JSON file.",
    "  --regression-threshold <n>    regression: max allowed error-count increase (default 0).",
    "",
    "Environment:",
    `  ${PROJECT_PATH_ENV_VAR.padEnd(30)}Unity project root; absolute, or relative to the cwd. Wins over --project-from-cwd.`,
    `  ${PORT_ENV_VAR.padEnd(30)}Optional port override.`,
    "  UNITY_PATH                     Unity Editor executable for batch-only tools.",
    "",
    "Examples:",
    `  ${binName} wait-for-ready`,
    `  ${binName} run-tool unity_open_mcp_ping --json`,
    `  ${binName} run-tool unity_open_mcp_list_assets --arg folder=Assets --arg max_per_folder=10`,
    `  ${binName} stream-events --follow`,
    `  ${binName} verify Assets/Prefabs --fail-on-severity warn`,
    `  ${binName} verify --mode scan-paths Assets/Scripts --profile balanced`,
    `  ${binName} baseline create --baseline-path CI/baseline.json`,
    `  ${binName} regression check --baseline-path CI/baseline.json --json`,
    `  ${binName} status --json`,
    `  ${binName} update --check`,
    `  ${binName} setup --client cursor                          run in the Unity project folder`,
    `  ${binName} setup --client cursor --unity-subpath Client   run in the repository root (monorepo)`,
    `  ${binName} ping --project-from-cwd --unity-subpath Client`,
    "",
    "Portable (committable) MCP client config — no machine paths:",
    `  ${binName} --project-from-cwd                        workspace IS the Unity project`,
    `  ${binName} --project-from-cwd --unity-subpath Client  Unity project in a subfolder`,
  ].join("\n");
}

export function setupHelpText(binName: string): string {
  return [
    `Usage: ${binName} setup --client <id> [--project <path>] [options]`,
    "",
    "Install or repair Unity Open MCP for one Unity project. This command does",
    "not require a running Unity Editor or bridge.",
    "",
    "Required:",
    "  --client <id>              cursor     .cursor/mcp.json",
    "                             claude     .mcp.json (Claude Code)",
    "                             vscode     .vscode/mcp.json (VS Code Copilot)",
    "                             codex      .codex/config.toml",
    "                             opencode   opencode.json",
    "                             agents     .mcp.json (generic agents)",
    "",
    "Project (first match wins; UNITY_PROJECT_PATH is ignored):",
    "  --project <path>           Unity root (Assets, Packages, ProjectSettings); absolute or relative.",
    "  --unity-subpath <rel>      Without --project: the Unity folder below the current directory.",
    "  (neither)                  The current directory is the Unity project.",
    "",
    "Options:",
    "  --skip-skill              Do not copy the bundled core skill.",
    "  --dry-run                 Show intended writes without changing files.",
    "  --json                    Emit a stable machine-readable report.",
    "  --help, -h                Show this help without requiring other flags.",
    "",
    "Portable config (no machine path — safe to commit):",
    "  --layout <l>              unity-root | monorepo (default: monorepo when --unity-subpath is set).",
    "  --unity-subpath <rel>     Unity root relative to the workspace, for example Client.",
    "  --workspace <path>        Repository root; defaults to the project minus --unity-subpath.",
    "  --portable                Write a committable entry with no machine path.",
    "  --no-portable             Write the absolute path.",
    "  --wrapper                 Also write the committed MCP wrapper script.",
    "",
    "  Client config and the agent skill are written under the workspace root; UPM pins",
    "  always go to the Unity project. Portable is the default for a monorepo and for a",
    "  workspace that is a git repository root. A project inside a larger repository is",
    "  configured where it is, with a warning naming the command to run from the root.",
    "",
    "  Examples:",
    "    cd MyGame && " + binName + " setup --client cursor",
    "    cd my-repo && " + binName + " setup --client cursor --unity-subpath Client",
    "",
    "Pins:",
    "  Every npm and UPM pin comes from this running package version. The command",
    "  installs only the bridge and verify Unity packages; domain packages are not installed.",
    "",
    "Exit codes:",
    "  0  success, including a successful dry-run",
    "  1  file read, parse, or write failure (including a config setup will not rewrite)",
    "  2  usage or validation error (project/client)",
    "",
    `Use '${binName} update' to update an existing MCP server installation;`,
    "use setup for first installation or repair of a Unity project.",
  ].join("\n");
}

export function versionText(version: string): string {
  return `unity-open-mcp ${version}`;
}
