using NUnit.Framework;
using UnityOpenMcpBridge;

namespace UnityOpenMcpBridge.Tests
{
    // M13 T4.3 — Per-project deterministic port resolution.
    //
    // Pins the hash formula + override precedence so it can never silently
    // drift from the MCP server's mirror (mcp-server/src/instance-discovery.ts).
    // Cross-side consistency is the whole point: the bridge and the MCP server
    // compute the same port for the same project path with zero shared config.
    //
    // If any constant here changes, update the matching test in
    // mcp-server/src/instance-discovery.test.ts in the same task.
    public static class InstancePortResolverTests
    {
        const string SamplePath = "/Users/foo/MyGame";
        const string SamplePathAlt = "/some/path";

        // Pinned cross-side values. Both sides MUST agree:
        //   /Users/foo/MyGame → port 22028, hash prefix dca5061f6f21537c
        //   /some/path        → port 29602, hash prefix eda6cf0b63f1a1d2
        // Generated by the same 8-byte-prefix SHA256 formula on both sides.
        const int SamplePathExpectedPort = 22028;
        const string SamplePathExpectedHashPrefix = "dca5061f6f21537c";
        const int SamplePathAltExpectedPort = 29602;

        // ----- hash + port formula -----

        [Test]
        public static void ProjectHash_IsStableAcrossCalls()
        {
            var a = InstancePortResolver.ProjectHash(SamplePath);
            var b = InstancePortResolver.ProjectHash(SamplePath);
            Assert.AreEqual(a, b, "Same path must hash to the same value");
        }

        [Test]
        public static void ProjectHash_IsLowercaseHexSha256()
        {
            var hash = InstancePortResolver.ProjectHash(SamplePath);
            Assert.AreEqual(64, hash.Length, "SHA256 hex digest is 64 chars");
            Assert.AreEqual(SamplePathExpectedHashPrefix, hash.Substring(0, 16),
                "First 8 bytes of the hash are pinned cross-side");
            foreach (var c in hash)
                Assert.IsTrue((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f'),
                    $"Hash must be lowercase hex, got '{c}'");
        }

        [Test]
        public static void ProjectHash_DifferentPaths_DifferentHashes()
        {
            var a = InstancePortResolver.ProjectHash(SamplePath);
            var b = InstancePortResolver.ProjectHash(SamplePathAlt);
            Assert.AreNotEqual(a, b, "Distinct paths must hash distinctly");
        }

        [Test]
        public static void ProjectHash_NormalizesBackslashesAndTrailingSlash()
        {
            var forward = InstancePortResolver.ProjectHash("/Users/foo/MyGame");
            var back = InstancePortResolver.ProjectHash("\\Users\\foo\\MyGame");
            var trailing = InstancePortResolver.ProjectHash("/Users/foo/MyGame/");
            Assert.AreEqual(forward, back, "Backslashes normalize to forward slashes before hashing");
            Assert.AreEqual(forward, trailing, "Trailing slash is trimmed before hashing");
        }

        [Test]
        public static void ComputePort_IsWithinRange()
        {
            var port = InstancePortResolver.ComputePort(SamplePath);
            Assert.GreaterOrEqual(port, InstancePortResolver.PortRangeStart);
            Assert.LessOrEqual(port, InstancePortResolver.PortRangeStart + InstancePortResolver.PortRangeSize - 1);
        }

        [Test]
        public static void ComputePort_MatchesPinnedCrossSideValue()
        {
            // If this breaks, the MCP server's mirror in instance-discovery.ts
            // has drifted from the bridge. Update both sides together.
            Assert.AreEqual(SamplePathExpectedPort, InstancePortResolver.ComputePort(SamplePath));
            Assert.AreEqual(SamplePathAltExpectedPort, InstancePortResolver.ComputePort(SamplePathAlt));
        }

        [Test]
        public static void ComputePort_DifferentPaths_LikelyDifferentPorts()
        {
            // Distinct paths almost always map to distinct ports; we only
            // assert that the two pinned paths differ (collisions on a
            // 10000-port range are rare but possible in theory).
            Assert.AreNotEqual(
                InstancePortResolver.ComputePort(SamplePath),
                InstancePortResolver.ComputePort(SamplePathAlt));
        }

        // ----- override precedence -----

        [Test]
        public static void ResolvePort_EnvOverrideWins()
        {
            var port = InstancePortResolver.ResolvePort(SamplePath, envPort: 19120, cliPort: null);
            Assert.AreEqual(19120, port);
        }

        [Test]
        public static void ResolvePort_CliArgWins_WhenEnvMissing()
        {
            var port = InstancePortResolver.ResolvePort(SamplePath, envPort: null, cliPort: 19120);
            Assert.AreEqual(19120, port);
        }

        [Test]
        public static void ResolvePort_EnvWinsOverCli()
        {
            var port = InstancePortResolver.ResolvePort(SamplePath, envPort: 21000, cliPort: 22000);
            Assert.AreEqual(21000, port, "Env var has higher precedence than CLI arg");
        }

        [Test]
        public static void ResolvePort_FallsBackToHash_WhenNoOverride()
        {
            var port = InstancePortResolver.ResolvePort(SamplePath, envPort: null, cliPort: null);
            Assert.AreEqual(SamplePathExpectedPort, port);
        }

        [Test]
        public static void ResolvePort_InvalidOverride_FallsBackToHash()
        {
            // Out-of-range values are rejected, not trusted.
            Assert.AreEqual(SamplePathExpectedPort,
                InstancePortResolver.ResolvePort(SamplePath, envPort: 0, cliPort: null),
                "Port 0 is invalid → fall through");
            Assert.AreEqual(SamplePathExpectedPort,
                InstancePortResolver.ResolvePort(SamplePath, envPort: 70000, cliPort: null),
                "Port 70000 is out of range → fall through");
            // When env is invalid but cli is valid, cli wins.
            Assert.AreEqual(19120,
                InstancePortResolver.ResolvePort(SamplePath, envPort: 0, cliPort: 19120));
        }

        [Test]
        public static void ResolvePort_ValidOverrideAtBoundaries()
        {
            Assert.AreEqual(1,
                InstancePortResolver.ResolvePort(SamplePath, envPort: 1, cliPort: null),
                "Port 1 is the minimum valid port");
            Assert.AreEqual(65535,
                InstancePortResolver.ResolvePort(SamplePath, envPort: 65535, cliPort: null),
                "Port 65535 is the maximum valid port");
        }

        // ----- paths -----

        [Test]
        public static void LockPath_EndsWithProjectHashJson()
        {
            var path = InstancePortResolver.LockPath(SamplePath);
            var expectedSuffix = InstancePortResolver.ProjectHash(SamplePath) + ".json";
            Assert.IsTrue(path.EndsWith(expectedSuffix),
                $"Expected lock path to end with {expectedSuffix}, got {path}");
            Assert.IsTrue(path.Replace('\\', '/').Contains(".unity-agent/instances/"),
                "Lock lives under ~/.unity-agent/instances/");
        }

        [Test]
        public static void LockPath_StableForSameProject()
        {
            var a = InstancePortResolver.LockPath(SamplePath);
            var b = InstancePortResolver.LockPath(SamplePath);
            Assert.AreEqual(a, b);
        }
    }
}
