// Regression: code-review finding B41 — run_id is caller-supplied (via the
// bridge body, bypassing the MCP schema under batch_execute) and interpolated
// straight into a filesystem path under ~/.unity-open-mcp. Without validation,
// values like "../../.." or "a/b" escaped the directory or invented subpaths.
// The fix adds TestRunnerService.IsValidRunId (whitelist [A-Za-z0-9._-], 1..128
// chars) and RunTestsTool rejects an invalid id before any file op.
using NUnit.Framework;
using UnityOpenMcpBridge.TestRunner;

namespace UnityOpenMcpBridge.Tests
{
    public class RunIdValidationTests
    {
        // -------------------------------------------------------------------
        // IsValidRunId — accepted forms.
        // -------------------------------------------------------------------

        [Test]
        public void IsValidRunId_AutoGeneratedForm_IsValid()
        {
            // The bridge-generated "<pid>-<unixMs>" form must always pass so the
            // auto-generation fallback is not rejected by its own validator.
            var auto = "12345-1700000000000";
            Assert.IsTrue(TestRunnerService.IsValidRunId(auto), auto);
        }

        [Test]
        public void IsValidRunId_LettersDigitsDotUnderscoreDash_IsValid()
        {
            Assert.IsTrue(TestRunnerService.IsValidRunId("abcDEF012"));
            Assert.IsTrue(TestRunnerService.IsValidRunId("run.1"));
            Assert.IsTrue(TestRunnerService.IsValidRunId("run_1"));
            Assert.IsTrue(TestRunnerService.IsValidRunId("run-1"));
            Assert.IsTrue(TestRunnerService.IsValidRunId("a.b-c_d"));
        }

        [Test]
        public void IsValidRunId_MaxLength_IsValid()
        {
            // Exactly MaxRunIdLength chars must be accepted (boundary).
            var id = new string('a', TestRunnerService.MaxRunIdLength);
            Assert.IsTrue(TestRunnerService.IsValidRunId(id),
                "exactly MaxRunIdLength chars must be valid");
        }

        // -------------------------------------------------------------------
        // IsValidRunId — rejected forms (the B41 security surface).
        // -------------------------------------------------------------------

        [Test]
        public void IsValidRunId_NullOrEmpty_IsInvalid()
        {
            Assert.IsFalse(TestRunnerService.IsValidRunId(null));
            Assert.IsFalse(TestRunnerService.IsValidRunId(""));
        }

        [Test]
        public void IsValidRunId_PathTraversal_IsInvalid()
        {
            // The headline B41 case — "../../.." must not escape StatusDir.
            Assert.IsFalse(TestRunnerService.IsValidRunId("../../.."));
            Assert.IsFalse(TestRunnerService.IsValidRunId(".."));
            Assert.IsFalse(TestRunnerService.IsValidRunId("./x"));
        }

        [Test]
        public void IsValidRunId_PathSeparators_IsInvalid()
        {
            Assert.IsFalse(TestRunnerService.IsValidRunId("a/b"));
            Assert.IsFalse(TestRunnerService.IsValidRunId("a\\b"));
        }

        [Test]
        public void IsValidRunId_Whitespace_IsInvalid()
        {
            Assert.IsFalse(TestRunnerService.IsValidRunId("a b"));
            Assert.IsFalse(TestRunnerService.IsValidRunId(" a"));
            Assert.IsFalse(TestRunnerService.IsValidRunId("a\tb"));
        }

        [Test]
        public void IsValidRunId_OtherSpecialChars_IsInvalid()
        {
            Assert.IsFalse(TestRunnerService.IsValidRunId("a:b"));
            Assert.IsFalse(TestRunnerService.IsValidRunId("a;b"));
            Assert.IsFalse(TestRunnerService.IsValidRunId("a*b"));
            Assert.IsFalse(TestRunnerService.IsValidRunId("a?b"));
            Assert.IsFalse(TestRunnerService.IsValidRunId("a|b"));
            Assert.IsFalse(TestRunnerService.IsValidRunId("a%b"));
            Assert.IsFalse(TestRunnerService.IsValidRunId("a$b"));
            Assert.IsFalse(TestRunnerService.IsValidRunId("a#b"));
            Assert.IsFalse(TestRunnerService.IsValidRunId("a@b"));
            Assert.IsFalse(TestRunnerService.IsValidRunId("a!b"));
            // Spaces inside a quoted JSON string are still part of the id.
            Assert.IsFalse(TestRunnerService.IsValidRunId("a b"));
        }

        [Test]
        public void IsValidRunId_OverMaxLength_IsInvalid()
        {
            // One char over the cap must be rejected so the filename cannot grow
            // unbounded (filesystem path limits, log noise).
            var id = new string('a', TestRunnerService.MaxRunIdLength + 1);
            Assert.IsFalse(TestRunnerService.IsValidRunId(id),
                "MaxRunIdLength+1 chars must be rejected");
        }
    }
}
